apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: haproxy-namespace
data:
  haproxy.cfg: |
    global
      stats timeout 30s
      user haproxy
      group haproxy
      daemon

    defaults
      log  global
      mode  tcp
      option  tcplog
      option  dontlognull
      timeout connect 5000
      timeout client  50000
      timeout server  50000
      errorfile 400 /etc/haproxy/errors/400.http
      errorfile 403 /etc/haproxy/errors/403.http
      errorfile 408 /etc/haproxy/errors/408.http
      errorfile 500 /etc/haproxy/errors/500.http
      errorfile 502 /etc/haproxy/errors/502.http
      errorfile 503 /etc/haproxy/errors/503.http
      errorfile 504 /etc/haproxy/errors/504.http

    frontend haproxynode
        bind *:9090
        mode tcp
        default_backend backendnodes

    frontend stats
        bind *:10001
        mode http
        stats enable
        stats uri /stats
        stats refresh 10s

    backend backendnodes
        balance source
        option tcplog
        server node1 localhost:80 check
