---
creation_rules:
  - path_regex: secrets\/dev\/.*\.(ya?ml)$
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      272CD863251659A309FE520049D3B4D4BB103232
  - path_regex: secrets\/int\/.*\.(ya?ml)$
  
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      272CD863251659A309FE520049D3B4D4BB103232
...
