apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:9zBL2F2kePVEccXBkeYBD8AUxsF7gAFCWoOD,iv:TSUAjRhbKGG3qbtHB4Iq4BkM15s7ijP/r8oQpAd3R8E=,tag:RZiJGXX6s8eL3l47LtT5rQ==,type:comment]
    username: ENC[AES256_GCM,data:tv/5fFEA+7I=,iv:zJKiuPRAHjlpITz2PVsdb2JJvNVbwhvoKpDMdIt2X1A=,tag:NTdWorYWnwDQwSoZlHIfmQ==,type:str]
    #ENC[AES256_GCM,data:/2L8lERrjrgaiO/rw0n+9AbXxZ94WCXqkuLAnZSU,iv:5N1A2nMTOS0TA5gEw5/ieJkddYt9CCCzocQWna9zL5g=,tag:oLOtnhevo4z7tzDuHiRoMQ==,type:comment]
    password: ENC[AES256_GCM,data:yc/yima0LToZNsBI,iv:CPdijfexvzHL7PK3Mx2iMyvapjM8W2XrfalaKACMZf4=,tag:4WpkK5c16KHo8h9MAVhzRg==,type:str]
sops:
    lastmodified: "2025-04-21T05:57:11Z"
    mac: ENC[AES256_GCM,data:/kwHw1rTw6lGqFb8ixmNrTnPpHV7qZZXEwwB9F0PD4ykRKDVYNh9GnqD3RME4ZKNcEvMZcszEB/bJergmU3AjN8Jd3DtVCeL0JpvvQfsolpCO/QqAqke7XEeanSq9x/TsF4qy7DeVU6NLwKiZUzlcHKHiZhn28TgOUAlH14Mqz4=,iv:wLY34z7t7eCFWesjNnGDGuF41KXL7VU7Obp6JTiVymw=,tag:grDLQWsHOahsV7PQK2rCMg==,type:str]
    pgp:
        - created_at: "2025-04-21T05:57:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA23ICO6FjlxxAQv9HcUlQ++78FpF6lLtNYrIGKacDj2NDh/PP252KI8hUQLl
            Bf9Osdl+r/7WFjk3GjS3A/j+pCyZKffE+k87HQbHjrk5VCfkuxTunAW5YFc4qvZo
            JZ7O5ouvveKY0uB2PwpgIAP8+uV+YIbWl8w99yX52506erS26gVMfdCjCTLRPCcF
            NVaSpXDPL5AR12V9PHh5hlaihkRoW+YbqgJErD2Sv56hwbqHr26Fmxxsg+ZIXsgT
            LQvVchOgJ/CS969xxFmadfAhB35aRdSYmDip0HPzave4XEq9RrdaINsbiMOKLsIf
            x7dRsgsGi5QcMSd/mEhlHpxD1eHGXabZk+s7DiWaZhB0TlAPWA8p6oA4oSiWuQSp
            2YUT4JdVN6rEi7f4/TFvVP/lDSt6CiFoYZtC3vfH4dRIk3C5TXFGgShmv2NewOKD
            kGkNZLVm7EM/KOOV45vkHhzr8ZNfWM8jKqHr2sWtWBpm4Se9lBVASNrZ7rfZeMLO
            XRbQ9I7RsUIMpJyY/GmA0lwBjK/1hE2R325LXWQsDgo4DLwvKESHntOYJhxLBZFT
            8pOrq9vFAi/M2Stta6I9erXRjhU3McmMLbtnW3TypwjTnpJl41vDKCD71Tj3AKDc
            LmpLQovcBscAKPCnng==
            =Lfv2
            -----END PGP MESSAGE-----
          fp: 8DDC9FF793E5CFBBDD8CBB2028EEB70E7F1A0827
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
