apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: test-secret-argocd
    namespace: karoly-boss-namespace
data:
    MY_SUPER_SECRET: ENC[AES256_GCM,data:Mi07SO+colsKFiuty+7Wh7yOUtS0FsMzKdXhdREIrCM=,iv:cqZdW3L3XwR3EQx52NTAqOfJ/V5vTePJd2EPSCJGB00=,tag:vsfCpYLUYGQiHE7xWMGHKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-06T11:19:49Z"
    mac: ENC[AES256_GCM,data:oxjNcEqS3FJcOcfSfP+jwtK2a/ePeXTWXc/4ku7Qi3B5N01/TmCnib9vPJ93s9Qzdcx7UKf7bjILRVrwOf/FWGmWw2cN2jPaCbCesV/s6ytTXXxL9UY+Ce4MW7e/+wwb0lz+0KYhmBTAqKXYE6QauQjCTp3xBG5SPU2Of+OHy8c=,iv:oftn03RTJefoxyqPzzGHLaLJBtu0EBQpLAHTOAvpumA=,tag:6L0HiiKggnxJ1l9CMHd0RA==,type:str]
    pgp:
        - created_at: "2025-08-06T11:19:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA/8M3uxPjrwuAQwAmLAJSryxlaimZ49g+lJw2+lzUmISBct5qKOnEFKL21+a
            sFsiTNArcf1MzZHAwebF58NYdjAjpMR1tPkLTLrmLtUbDpmAFSh/MyBemG3aEwZS
            W/kzSzclfO5t5l8Oe7syvCiUt9rahGSZm/Fc5ATvwmksUdYZi3V8N8HUUHYcG4UD
            2vEhrMhjAtNOvvrN9wkoyvhfsNIbLwMvcqgugN6pzx0qAx3F+KVtN+7pBsX662MO
            m2CLDLL0sXRE9BXMz4gYjStkyjhENEzjgxoJG77HK2jDYloN2FjGaxuVNwl02fQ5
            4bHW4LJsm5EdhowC/s38E2cDNNeLxayQ6gpS0lEbX0SVzUw1EmwZ0fxCx0USEPVT
            zOK8PGowHgglQm0cy/anzoQMGzssKvqdqocIhflbRT4qJYQPdmXxVsJUOwfvlw/h
            1oZFexh1KJvvQXVyu259dFrmeu9pUVl9Xdrpkkg5XyGwIPIwsSdF68wn6wXrZryX
            n48166TZhD+FGf0cdLG31GgBCQIQ4CXQzmr5bVeEVNp9V7KXZgAyyvrgQBqecvvL
            uus2hfSskVRtwhiUnc8s4fcM0CDO/7s71Rm4mmMggX/LGi9dgjMSZAJ84ytYWylE
            I1L7kRbMM4z6ykquvc5n1Z3yucPKuR39Bw==
            =Arbj
            -----END PGP MESSAGE-----
          fp: 272CD863251659A309FE520049D3B4D4BB103232
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Secret for Petclinic
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: petclinic-secret-argocd
    namespace: petclinic-namespace
data:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:7emaa6cLVsANBJiY,iv:vXyCzaBDDqEGtuCROrGRZWsfy+Lfh0pdf+1HVWeK3mA=,tag:orJUAbEpf0Ms7Rtt7JczfA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:UGYjfHgfbo1ByNrb,iv:RneYY53fdAf5l3sIsUzpAabbTIZL2AAL0rlE1zwjq6U=,tag:jKObkN2JIvDttu0Q3ch5xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-06T11:19:49Z"
    mac: ENC[AES256_GCM,data:oxjNcEqS3FJcOcfSfP+jwtK2a/ePeXTWXc/4ku7Qi3B5N01/TmCnib9vPJ93s9Qzdcx7UKf7bjILRVrwOf/FWGmWw2cN2jPaCbCesV/s6ytTXXxL9UY+Ce4MW7e/+wwb0lz+0KYhmBTAqKXYE6QauQjCTp3xBG5SPU2Of+OHy8c=,iv:oftn03RTJefoxyqPzzGHLaLJBtu0EBQpLAHTOAvpumA=,tag:6L0HiiKggnxJ1l9CMHd0RA==,type:str]
    pgp:
        - created_at: "2025-08-06T11:19:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA/8M3uxPjrwuAQwAmLAJSryxlaimZ49g+lJw2+lzUmISBct5qKOnEFKL21+a
            sFsiTNArcf1MzZHAwebF58NYdjAjpMR1tPkLTLrmLtUbDpmAFSh/MyBemG3aEwZS
            W/kzSzclfO5t5l8Oe7syvCiUt9rahGSZm/Fc5ATvwmksUdYZi3V8N8HUUHYcG4UD
            2vEhrMhjAtNOvvrN9wkoyvhfsNIbLwMvcqgugN6pzx0qAx3F+KVtN+7pBsX662MO
            m2CLDLL0sXRE9BXMz4gYjStkyjhENEzjgxoJG77HK2jDYloN2FjGaxuVNwl02fQ5
            4bHW4LJsm5EdhowC/s38E2cDNNeLxayQ6gpS0lEbX0SVzUw1EmwZ0fxCx0USEPVT
            zOK8PGowHgglQm0cy/anzoQMGzssKvqdqocIhflbRT4qJYQPdmXxVsJUOwfvlw/h
            1oZFexh1KJvvQXVyu259dFrmeu9pUVl9Xdrpkkg5XyGwIPIwsSdF68wn6wXrZryX
            n48166TZhD+FGf0cdLG31GgBCQIQ4CXQzmr5bVeEVNp9V7KXZgAyyvrgQBqecvvL
            uus2hfSskVRtwhiUnc8s4fcM0CDO/7s71Rm4mmMggX/LGi9dgjMSZAJ84ytYWylE
            I1L7kRbMM4z6ykquvc5n1Z3yucPKuR39Bw==
            =Arbj
            -----END PGP MESSAGE-----
          fp: 272CD863251659A309FE520049D3B4D4BB103232
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
