apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/replace-deployment-image.yaml
  target:
    name: haproxy-deployment
    kind: Deployment

- path: patches/replace-mysql-image.yaml
  target:
    name: spring-petclinic
    kind: Deployment

- path: patches/set-replicas.yaml
  target:
    name: nginx-deployment
    kind: Deployment

- path: patches/modify-volume-sizes.yaml
  target:
    name: nginx-data
    kind: PersistentVolume

- path: patches/modify-pvc.yaml
  target:
    name: nginx-pvc
    kind: PersistentVolumeClaim

generators:
- secret-generators/int-secret-generator.yaml
